# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d81afbf8f2545e192cc6f6be12fe55f1d37bb7e05f42d718ac2768c6f0b45e6444d0b076aec5dba5d3876ed2d3bb724287b7d09e39957a09a3184c36a8de79ea

test:
  secret_key_base: 91cd5ba543418ca0a9816e2e997e28fd24e00ea8f08567c084da89fb6fe94c77559ed4b010567c4a401c78243f6b3b6d600aa90dc9ef134ae62022b516195ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
